name: Anchor BuildX

on:
  push:
    branches:
      - test-sample-action
  pull_request:
    branches:
      - test-sample-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test anchor
        uses: tanmaymunjal/anchor-ci@v0.2-beta-testing
